name: DevOps Pipeline

on:
  push: false
    branches:[ main ]
  pull_request:

jobs:

# ---------------- LINT ----------------
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Python lint
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install flake8
      - run: flake8 api worker || true

      # Node lint
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - run: |
          cd frontend
          npm install
          npx eslint . || true

      # Dockerfile lint
      - name: Hadolint
        run: |
          docker run --rm -i hadolint/hadolint < api/Dockerfile || true
          docker run --rm -i hadolint/hadolint < worker/Dockerfile || true
          docker run --rm -i hadolint/hadolint < frontend/Dockerfile || true

# ---------------- TEST ----------------
  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          pip install pytest pytest-cov
          pip install -r api/requirements.txt

      - name: Run tests
        run: |
          pytest api --cov=api --cov-report=xml || true

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

# ---------------- BUILD ----------------
  build:
    runs-on: ubuntu-latest
    needs: test

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v4

      - name: Build API image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: false
          tags: |
            localhost:5000/api:latest
            localhost:5000/api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Worker image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: false
          tags: |
            localhost:5000/worker:latest
            localhost:5000/worker:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          tags: |
            localhost:5000/frontend:latest
            localhost:5000/frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
            

# ---------------- SECURITY SCAN ----------------
  security:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Build images again (needed for Trivy)
        run: |
          docker build -t api:latest ./api
          docker build -t worker:latest ./worker
          docker build -t frontend:latest ./frontend

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: api:latest
          format: table
          exit-code: 1
          severity: CRITICAL

# ---------------- INTEGRATION TEST ----------------
  integration:
    runs-on: ubuntu-latest
    needs: security

    steps:
      - uses: actions/checkout@v4

      - name: Start full stack
        run: docker compose up -d --build

      - name: Wait for API
        run: sleep 20

      - name: Test job flow
        run: |
          curl -X POST http://localhost:3000/job

      - name: Shutdown stack
        run: docker compose down

# ---------------- DEPLOY ----------------
  deploy:
    runs-on: ubuntu-latest
    needs: integration
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Simulated rolling deploy
        run: |
          docker compose up -d --build
          sleep 10
          docker compose ps